### ISSUE TITLE
src/process_fastword_embeddings.py is missing...

### ISSUE THREAD

**Issue by BoxuanMa** [bzylich/linguistic-skill-modeling#1]
Hi, I plan to run DKT or DAS3H with word embeddings, but I can't find the src/process_fastword_embeddings.py file to retrieve all the necessary word embeddings for the dataset.

**Comment by bzylich** [comment]
Hi, sorry about this. I have added the file to the src directory. Thanks for letting me know this was missing!

**Comment by BoxuanMa** [comment]
> Hi, sorry about this. I have added the file to the src directory. Thanks for letting me know this was missing!

Thanks for adding this!  It's a very interesting work and I can't wait to run the code!
